### ISSUE TITLE
1.1 Roadmap

### ISSUE THREAD

**Issue by qwrtln** [Heegu-sama/Homm3BG#134]
Must have:
 - [ ] Make cover count as page 1
 - [ ] Make sure the document has an even number of pages at all times. This can be achieved via adding a one-page section like "Notes", which will be included optionally.
 - [ ] Add players aid on the back cover.
 - [ ] Add missing 4L movement token to the setup page.
 - [ ] Come up with a solution to store binary blobs outside the repository.

Nice to have:
 - [ ] Create a poor man's printable build - black and white with no background image.

**Comment by qwrtln** [comment]
@Heegu-sama please add your tasks.

**Comment by evilmint** [comment]
Suggestion from my side: Would a pre-commit/push hook to run po4a be a helpful thing?

**Comment by DarthGandalf** [comment]
> Add players aid on the back cover.

Suggestion from my side: make player aid a separate page instead - because it would be one per player, so in several copies.

On the back cover it would be very useful to have the mapping of difficulty X level to which neutral units to use - this table is used in exploration very often, so I need to go to the Difficulty page in the book very often.

**Comment by qwrtln** [comment]
@DarthGandalf, interesting idea. Would you be like to draft a PR with this?

**Comment by DarthGandalf** [comment]
The players aid would be a separate pdf, therefore separate .tex file etc.

Re difficulty table - I don't know how it should be done :) I don't want to duplicate the table in two places, so probably it should be moved from Difficulty, but then I don't know what to put there.

Probably details for both these ideas should be discussed in separate issues though, not "roadmap"

**Comment by qwrtln** [comment]
Cool, reach out to me on Discord, my username over there is the same.
