### ISSUE TITLE
🇫🇷 French translation

### ISSUE THREAD

**Issue by qwrtln** [Heegu-sama/Homm3BG#157]
Progress:
- [x] title_page.tex #194 
- [x] introduction.tex #218 
- [x] game_modes.tex #220 
- [x] setup.tex #225 
- [x] round_structure.tex #275
- [x] player_turns.tex #258 
- [x] heroes.tex #260 
- [x] deckbuilding.tex #262 
- [x] resources.tex #271 
- [x] town.tex #270 
- [x] map_elements.tex #269 
- [x] units.tex #288 
- [x] combat.tex #291 
- [x] ai_heroes.tex #292 
- [x] difficulty #299 
- [x] scenario_end.tex #298 
- [x] trading.tex #293 
- [x] expansion_content.tex #297 
- [x] all_map_locations.tex #295 
- [x] credits.tex #319 
- [x] index.tex #319
- [x] notes.tex #319
- [x] back_cover.tex #319

**Comment by qwrtln** [comment]
To anyone willing to help with French translation, please reach out to `qwrtln` on Discord. Thanks.

**Comment by Legrecofr** [comment]
Add me I’ll try my best to help
