### ISSUE TITLE
🇷🇺 Russian translation

### ISSUE THREAD

**Issue by ohgodnotagain** [Heegu-sama/Homm3BG#284]
Progress:
- [x] title_page.tex #268 
- [x] introduction.tex #242 
- [x] components.tex #596
- [x] game_modes.tex #263
- [x] setup.tex #263
- [x] round_structure.tex #267 
- [x] player_turns.tex #279 
- [x] heroes.tex #283 
- [x] deckbuilding.tex #300 
- [x] resources.tex #301
- [x] town.tex #303
- [x] map_elements.tex #321 
- [x] units.tex #338 
- [x] combat.tex #409 
- [x] ai_rules.tex - #595 
- [x] difficulty - #616 
- [x] trading - #627 #630
- [x] scenario_end.tex #598
- [x] expansion_content.tex #618 
- [x] all_map_locations.tex #622 
- [x] credits.tex #625 
- [x] index.tex #626 
- [x] notes.tex #626 
- [x] back_cover.tex #626 

TODO:
- [x] de-capitalize
- [x] Способности -> навыки
- [x] punctuation
- [x] магическая стрела -> волшебная стрела
- [x] постройки - здания
- [x] artifact fluff - translation??
- [x] fix index #646 
- [x] конратака -> контрудар (units section)
- [x] специальность: либо везде с заглавной, либо с маленькой
- [x] Фракция -> фракция
- [x] fix fuzzy #632 
- [x] ИИ герои -> герои ИИ
- [x] check / fix printable version
- [x] артефакты: малый / великий / реликвия

**Comment by gerKirov** [comment]
> Progress:
> - [x] title_page.tex #268 
> - [x] introduction.tex #242 
> - [x] game_modes.tex #263
> - [x] setup.tex #263
> - [x] round_structure.tex #267 
> - [x] player_turns.tex #279 
> - [x] heroes.tex #283 
> - [ ] deckbuilding.tex #300 
> - [ ] resources.tex #301
> - [ ] town.tex #303
> - [ ] map_elements.tex
> - [ ] units.tex
> - [ ] combat.tex
> - [ ] ai_heroes.tex
> - [ ] scenario_end.tex
> - [ ] other_rules.tex
> - [ ] expansion_content.tex
> - [ ] all_map_locations.tex
> - [ ] credits.tex
> - [ ] index.tex
> - [ ] notes.tex
> - [ ] back_cover.tex
> 
> TODO:
> - [ ] de-capitalize
> - [ ] Способности -> навыки
> - [ ] punctuation
> - [ ] магическая стрела - волшебная стрела
> - [ ] постройки - здания
> - [ ] artifact fluff - translation??
>

**Comment by gerKirov** [comment]
> Progress:
> - [x] title_page.tex #268 
> - [x] introduction.tex #242 
> - [x] game_modes.tex #263
> - [x] setup.tex #263
> - [x] round_structure.tex #267 
> - [x] player_turns.tex #279 
> - [x] heroes.tex #283 
> - [ ] deckbuilding.tex #300 
> - [ ] resources.tex #301
> - [ ] town.tex #303
> - [ ] map_elements.tex
> - [ ] units.tex
> - [ ] combat.tex
> - [ ] ai_heroes.tex
> - [ ] scenario_end.tex
> - [ ] other_rules.tex
> - [ ] expansion_content.tex
> - [ ] all_map_locations.tex
> - [ ] credits.tex
> - [ ] index.tex
> - [ ] notes.tex
> - [ ] back_cover.tex
> 
> TODO:
> - [ ] de-capitalize
> - [ ] Способности -> навыки
> - [ ] punctuation
> - [ ] магическая стрела - волшебная стрела
> - [ ] постройки - здания
> - [ ] artifact fluff - translation??
>

**Comment by qwrtln** [comment]
Map elements is broken, please fix this

**Comment by ohgodnotagain** [comment]
> Map elements is broken, please fix this

https://github.com/Heegu-sama/Homm3BG/pull/403

**Comment by DarthGandalf** [comment]
Я думаю, слово фракция тоже лучше с маленькой
