### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by qwrtln** [Heegu-sama/Homm3BG#86]
Creating this to track work that needs to be done for 1.0.0.

Must haves:
 - [x] #84
 - [x] #80
 - [x] #87 
 - [x] Reiterate on what happens when all your units are defeated
 - [x] Chiss's remarks
 - [x] Add a box about rules priority
 - [x] Level ups are resolved before visiting a field.
- [x] General timings of cards, and if you can use them outside of combat etc.
- [x] Try to explain the use of +attack and +defense cards properly. The current example for them is great but they could be introduced at some point.
 - [x]  Clarification: If AI heroes are instructed to draw a card, they draw another one from the AI deck.
 - [x] Re-read by @Heegu-sama 
 - [x] Read by @Heegu-sama's fiancé ;-)
 - [x] Re-structure AI heroes/AI combat sections into a more logical order, promote Campaign/AI heroes to a big section heading.
 - [x] #119 
 
 Nice to haves:
  - [x] #82
  - [x] ~~Add Player's Aid section~~
  - [x] #108 
  - [x] #88
  - [x] #95 
  - [x] Fix layout on page with ranged example
  - [ ] Add pictures of units with summon ability
  - [x] #102 
  - [x] #114 
  
Meh:
 - [x] #93 
 - [x] #98 
 - [x] #105

**Comment by Heegu-sama** [comment]
- [ ] I need to apply the rest of Chiss's remarks.

**Comment by Heegu-sama** [comment]
- [ ] Request someone to post pictures of cards from the inferno expansion that can summon units. I need to see if all the information in the inferno rule book about summons really needs to be added.
- [ ] Re-read the entire thing and edit anything that looks off. There's many chunks that probably should be pruned.
- [ ] Have my fiancee read it. She's a Finnish-English-Finnish translator too.

**Comment by Heegu-sama** [comment]
- [ ] Add a box about rules priority.

**Comment by Heegu-sama** [comment]
- [ ] Mention that losing a combat with your main hero when you own no towns/settlements also leads to play elimination.

**Comment by Heegu-sama** [comment]
Try to clarify these things, as asked by BGG members:
- [ ] Level ups are resolved before visiting a field.
- [ ] General timings of cards, and if you can use them outside of combat etc.
- [ ] Try to explain the use of +attack and +defense cards properly. The current example for them is great but they could be introduced at some point.

**Comment by Heegu-sama** [comment]
- [ ] Clarification: If AI heroes are instructed to draw a card, they draw another one from the AI deck.
